Repository Aicemelt/Tropical-frontend, pull requests merged in 2025-09, with the labels that each got.

#7 [Bug]: scss import 에러 수정(#6)
  package-lock.json
  package.json
  src/App.jsx
  src/asset/arrow-w.svg
  src/asset/check.png
  src/asset/date.png
  src/asset/delete.png
  src/asset/edit.png
  src/asset/next.png
  src/asset/pencil-32.png
  src/asset/plus-32-w.png
  src/asset/plus-32.png
  src/asset/prev.png
  src/components/bucket/BucketFilter.jsx
  src/components/bucket/BucketInput.jsx
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketList.jsx
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarDay.jsx
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarHeader.jsx
  src/components/common/Buttons.jsx
  src/components/common/DatePicker.jsx
  src/components/common/LeftHeader.jsx
  src/components/common/RightHeader.jsx
  src/components/smalltalk/SmallTalkList.jsx
  src/components/smalltalk/Tips.jsx
  src/components/todo/TodoFilter.jsx
  src/components/todo/TodoInput.jsx
  src/components/todo/TodoItem.jsx
  src/components/todo/TodoList.jsx
  src/layouts/LeftLayout.jsx
  src/layouts/RightLayout.jsx
  src/pages/BucketPage.jsx
  src/pages/CalendarPage.jsx
  src/pages/TodoPage.jsx
  src/styles/components/Buttons.module.scss
  src/styles/components/Calendar.module.scss
  src/styles/components/CalendarDay.module.scss
  src/styles/components/CalendarGrid.module.scss
  src/styles/components/CalendarHeader.module.scss
  src/styles/components/DatePicker.module.scss
  src/styles/components/Filter.module.scss
  src/styles/components/Header.module.scss
  src/styles/components/Input.module.scss
  src/styles/components/Item.module.scss
  src/styles/components/SmallTalkItem.module.scss
  src/styles/components/SmallTalkList.module.scss
  src/styles/components/Tips.module.scss
  src/styles/global.scss
  src/styles/layouts/Layout.module.scss
Labels: bug, frontend, priority: medium, design

#18 [Feat]: Todo 및 버킷리스트 CRUD 기능 구현 (#12)
  src/components/bucket/BucketFilter.jsx
  src/components/bucket/BucketInput.jsx
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketList.jsx
  src/components/common/DatePicker.jsx
  src/components/common/RightHeader.jsx
  src/components/todo/TodoFilter.jsx
  src/components/todo/TodoInput.jsx
  src/components/todo/TodoItem.jsx
  src/components/todo/TodoList.jsx
  src/hooks/bucket/useBucketApi.js
  src/hooks/todo/useTodosApi.js
  src/pages/BucketPage.jsx
  src/pages/TodoPage.jsx
  src/store/bucketStore.js
  src/store/todoStore.js
  src/styles/components/Filter.module.scss
Labels: feature, frontend, priority: high, STATUS : IN PROGRESS

#19 [Feat]: 프론트엔드 인증 및 온보딩 플로우 시스템 구축 (#15, #16, #17)
  src/components/auth/Guards/ProtectedRoute.jsx
  src/components/onboarding/ConsentItem.jsx
  src/components/onboarding/ConsentList.jsx
  src/components/onboarding/OnboardingActions.jsx
  src/components/onboarding/OnboardingIntro.jsx
  src/components/welcome/SocialLoginButton.jsx
  src/components/welcome/SocialLoginList.jsx
  src/components/welcome/WelcomeContent.jsx
  src/components/welcome/WelcomeFooter.jsx
  src/components/welcome/WelcomeHeader.jsx
  src/hooks/auth/useAuthStatus.js
  src/pages/OnboardingPage.jsx
  src/pages/WelcomePage.jsx
  src/routes/route-config.jsx
  src/services/api.js
  src/store/authStore.js
  src/styles/components/ConsentItem.module.scss
  src/styles/components/ConsentList.module.scss
  src/styles/components/OnboardingActions.module.scss
  src/styles/components/OnboardingIntro.module.scss
  src/styles/components/SocialLoginButton.module.scss
  src/styles/components/SocialLoginList.module.scss
  src/styles/components/WelcomeContent.module.scss
  src/styles/components/WelcomeFooter.module.scss
  src/styles/components/WelcomeHeader.module.scss
  src/styles/pages/OnboardingPage.module.scss
  src/styles/pages/WelcomePage.module.scss
  vite.config.js
Labels: feature, enhancement, frontend, help wanted, performance, priority: medium, design, STATUS : IN PROGRESS

#26 [Enhance]: 캘린더 기능 고도화 및 API 클라이언트 보안 강화 (#22, #24, #25)
  package-lock.json
  package.json
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarHeader.jsx
  src/services/api.js
  src/services/holidayService.js
  src/styles/components/Calendar.module.scss
Labels: bug, feature, enhancement, frontend, performance, security, refactor, priority: medium, design, STATUS : IN PROGRESS

#14 [Feat]: 일기 API 연동 및 상태관리 구현 및 일기/일정 API 버전 명시
  src/components/diary/EmotionSelector.jsx
  src/components/diary/EmotionSelector.scss
  src/components/diary/WeatherSelector.jsx
  src/components/diary/WeatherSelector.scss
  src/hooks/diary/useDiary.js
  src/services/api.js
  src/services/diaryApi.js
  src/store/diaryStore.js
Labels: feature, enhancement, frontend, priority: medium

#33 [doc]: 프론트엔드 프로젝트 가이드 README 수정
  README.md
Labels: docs

#32 [Feat]: API 인증 개선, 날짜 필터링 버그 수정, 페이지 전환 애니메이션 구현 (#20, #21, #27)
  package-lock.json
  package.json
  src/components/common/DatePicker.jsx
  src/components/common/PageTransition/PageTransition.jsx
  src/components/common/RightHeader.jsx
  src/hooks/bucket/useBucketApi.js
  src/hooks/todo/useTodosApi.js
  src/layouts/LeftLayout.jsx
  src/layouts/RightLayout.jsx
  src/routes/route-config.jsx
  src/services/api.js
  src/store/todoStore.js
  src/styles/components/Filter.module.scss
Labels: bug, enhancement, frontend, priority: high, STATUS : IN PROGRESS
